### ISSUE TITLE
Support landscape mode

### ISSUE THREAD

**Issue by xmha97** [CliffracerMerchant/SoundAura#13]
Please support landscape mode

**Comment by CliffracerMerchant** [comment]
Sorry, I disabled landscape mode temporarily due to an apparent bug with the Accompanist library window insets. It appears to have been fixed, so it shouldn't be that difficult to re-enable it. I'll try to work on it tomorrow.

**Comment by xmha97** [comment]
Thanks.

**Comment by xmha97** [comment]
Thanks.
