### ISSUE TITLE
Preset

### ISSUE THREAD

**Issue by NSTAdventure** [CliffracerMerchant/SoundAura#16]
Hi can you add preset feature like noice app?
I think it would be cool instead i should remember what audio that i usually play together

**Comment by CliffracerMerchant** [comment]
Sure, it shouldn't be too difficult to implement on the back-end side of things. The only problem is I'm not too sure how to handle the UI implementation of it. One idea is I could add another floating action button that opens into a popup where you can select and add/remove presets. The downside to that is that there would then be three FABs >_>. I suppose I'll start working on the functionality for now and worry about the UI side of things once I get there.

**Comment by NSTAdventure** [comment]
> Sure, it shouldn't be too difficult to implement on the back-end side of things.

Thanks 🙏
