### ISSUE TITLE
Alarm timer

### ISSUE THREAD

**Issue by NSTAdventure** [CliffracerMerchant/SoundAura#18]
Problem:
1. Insomnia or you have problem related to sleeping 
2. You also may have problem wake up in the morning

Solution:
Add timer or schedule
The preset or any audio that has been selected by user will played for X time then it will stop playing after timer end

**Comment by CliffracerMerchant** [comment]
So do you want both a play for x amount of time feature, and and an alarm feature that starts playing at a scheduled time?
I can definitely do the play for x amount of time feature after I finish the presets, but I'm not sure about the alarm. It might be difficult to fit all of these features into the UI in a cohesive way, but if I can think of a way I'll try.

**Comment by NSTAdventure** [comment]
> So do you want both a play for x amount of time feature, and and an alarm feature that starts playing at a scheduled time?
> I can definitely do the play for x amount of time feature after I finish the presets, but I'm not sure about the alarm. It might be difficult to fit all of these features into the UI in a cohesive way, but if I can think of a way I'll try.

Yeah something like that dev.
Dev i have such hard time to explain those feature what a horsemen of the annoyance.
(Btw all my ideas is from noice app)

**Comment by natewind** [comment]
@CliffracerMerchant How do I access the timer? I can’t find it anywhere in the app

**Upd:** Never mind, it’s long press on play/pause.
