### ISSUE TITLE
Create a time gap.

### ISSUE THREAD

**Issue by sak96** [CliffracerMerchant/SoundAura#20]
Some sound might be played once every 5 min.
- Thunder
- Wolf's cry
- etc.

ps: this app works wonders.

**Comment by CliffracerMerchant** [comment]
I'm not sure if there is a way to accomplish this without polluting the UI too much. I suppose an 'Add repeat delay' option could be added to each track's options menu. On the database side of things, a repeat delay could be added to each track in the 'track' database table. The Player class defined in 'Player.kt' file could have this delay as a field initialized by a new constructor parameter, and could then handle the delay on the playback side of things.

To be honest, I don't think I would use this feature myself. I am sort of busy right now between adding other features to this this app and personal stuff, so I think I'm going to have to pass on adding it myself. If you want to try adding it in a fork I would be happy to help with any questions you have.

Personally I would bypass this issue by using a long premixed track with the, e.g. thunder, effects already spaced throughout the track at the intervals you would like. Obviously you lose customizability and increase file size with this approach, but I think the reduced hassle is worth it. It also allows for a more randomized interval between repeat sounds that is more realistic than a constant interval anyways if you're dealing with a thunder sound effect. You might find longer tracks with a mixture of sound effects to mimic different environments on, e.g., popular video sharing websites. You could then download them and convert them to audio files to add to SoundAura.

**Comment by sak96** [comment]
sure i will look into Player.kt and try to figure out the  code. also i think workaround could be extending the thunder effect clip by adding blank sound if it possible

**Comment by sak96** [comment]
@CliffracerMerchant  closing the issue, i don't think this is very much required feature.
if required will raise pr and re-open issue.

**Comment by opk12** [comment]
To add a use case: tracking the time to change posture in qi gong, or to enter the next phase of meditation, through a discreet sound (gong / bird / wood crack / ...) so the mind can stay empty.
