### ISSUE TITLE
Filter list based on it is enabled or not.

### ISSUE THREAD

**Issue by sak96** [CliffracerMerchant/SoundAura#21]
if you add too many sound clips and enable few.
then trying to disable anyone of the enabled once might need lot of scrolling.

The filter could also be order by enabled/disabled.

**Comment by sak96** [comment]
if you could point out the way to proceed may be i can try to add it myself.

**Comment by CliffracerMerchant** [comment]
As you suggested, I think it would be best to add this as a toggled option. That way the tracks could be sorted by their enabled state, and then sorted by another metric (alphabetically, order added, etc.). If it were done this way it would prevent the number of available sorting options from being too large.

I think I can do this myself as it shouldn't take too long. I'll probably just add the toggle option at the top of the sorting menu popup that appears when you tap/click the sorting icon in the top app bar.
