### ISSUE TITLE
Thanks for this great app !!!

### ISSUE THREAD

**Issue by heartlog** [CliffracerMerchant/SoundAura#24]
I found about the `soundaura` on f-droid, this is most useful productivity app i can ever dream of !!!
😊😊😊
By **background playback** i can hear my fav piano track while watching lecture...
This application is underrated..Keep your work going !! 
if i had to rate this apk, i would have rated 5/5 stars....
Thanks a lot...

**Regard Heartlog**

**Comment by CliffracerMerchant** [comment]
Thanks a lot, I'm glad you like it 😊
