### ISSUE TITLE
Play/Stop button

### ISSUE THREAD

**Issue by xmha97** [CliffracerMerchant/SoundAura#26]
Hi, please add an option to change button function.
I need Play/Stop button instead of Play/Pause button.

**Comment by CliffracerMerchant** [comment]
I'm not sure I understand what the use case is for a stop button. The button only toggles between play and pause because it is assumed that the audio being played is background ambient sound, for which it shouldn't really be noticeable if it pauses and resumes instead of stops and restarts. It wouldn't be too difficult to implement this, I'm just hesitant to add too many options to the settings screen unless it's necessary.

**Comment by xmha97** [comment]
> I'm not sure I understand what the use case is for a stop button. The button only toggles between play and pause because it is assumed that the audio being played is background ambient sound, for which it shouldn't really be noticeable if it pauses and resumes instead of stops and restarts. It wouldn't be too difficult to implement this, I'm just hesitant to add too many options to the settings screen unless it's necessary.

I know exactly what this app is and what it does, but I want to use this app as an audio mixer (mix a vocal with an instrumental)!

**Comment by CliffracerMerchant** [comment]
I suppose I can add this as an option in the settings screen.

**Comment by xmha97** [comment]
> I suppose I can add this as an option in the settings screen.

It's good.

**Comment by CliffracerMerchant** [comment]
Sorry it's taken me forever to get around to this. I haven't had as much time to work on the app as I would've liked, and some of the other features I've been adding took me a lot longer than expected. Do you still plan on using this feature if it is added? I just wanted to make sure in case you found another app that accomplishes this.

**Comment by xmha97** [comment]
> Sorry it's taken me forever to get around to this. I haven't had as much time to work on the app as I would've liked, and some of the other features I've been adding took me a lot longer than expected. Do you still plan on using this feature if it is added? I just wanted to make sure in case you found another app that accomplishes this.

Yes, I want to use this feature.

**Comment by xmha97** [comment]
Thanks. <3
