### ISSUE TITLE
Android 13: add generic picture to display

### ISSUE THREAD

**Issue by firefoxlover** [CliffracerMerchant/SoundAura#27]
Awesome app! On Android 13 there is a big display of the running music app, a nice cover image would be awesome.

**Comment by CliffracerMerchant** [comment]
Good idea; personally I just hide the notification and control the app entirely with the quick settings tile, so I tend to forget about the notification >_>. I suppose I'll just make it be a blown up app icon, possibly with a less contrasting background color.
